### PR TITLE
add tests, bump version

### PR DESCRIPTION
**Pull request by devoncarew**
Hey Seth, here's some tweaks for this library. I'm thinking about using it to eliminate some load delay in dartpad.

- whitespace trimming
- remove the pubspec.lock file
- bump the version to `0.1.0` (this seems like a good, 'you can use this now' indicator)
- add two tests of the transformer

### CODE REVIEW

**Comment by devoncarew** [comment]
ping -

**Comment by sethladd** [comment]
whoa, sorry! totally missed this.

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
Published!

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by zoechi** [comment]
@maxwellpeterson-wf usually add reaction on the initial post is preferred over +1 comments.

**Comment by maxwellpeterson-wf** [comment]
Sorry, it's a part of our compliance process.

**Pull request merged**
