### PR TITLE
Updating to non deprecated dependencies.

### PR DESCRIPTION
**Pull request by domesticmouse**
Hey Seth, mind if I get rid of some complaints in the stagehand generated code?

### CODE REVIEW

**Comment by sethladd** [comment]
Awesome!

**Comment by sethladd** [comment]
Just pushed 0.1.0+3. Let me know if that works for you.

**Comment by domesticmouse** [comment]
Much betterer. Thanks!

**Comment by maxwellpeterson-wf** [comment]
+1

**Pull request merged**
