### PR TITLE
remove csp handling; bump version

### LINKED ISSUE #4: don't think the csp option is needed anymore
With a ~recent change, dart2js no longer generates both the regular and the csp JS. We user need to specify which type to generate (and the output file name). So, I think generally the csp file will no longer be call `precompiled`.

https://github.com/sethladd/dart_to_js_script_rewriter/blob/master/lib/dart_to_js_script_rewriter.dart#L52

### PR DESCRIPTION
**Pull request by devoncarew**
Fix #4.

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
@devoncarew do we need to update the README? It still mentioned CSP

**Comment by devoncarew** [comment]
Yup, missed that.

**Comment by maxwellpeterson-wf** [comment]
+1

**Pull request merged**
